### ISSUE TITLE
[Feature Request]: Run existing Tekton Tasks/ClusterTasks using the SDK

### ISSUE THREAD

**Issue by piotrpdev** [opendatahub-io/data-science-pipelines-tekton#121]
### Feature description

There are many existing Tasks/ClusterTasks available online e.g. through [TektonHub](https://hub.tekton.dev/), it would be nice if you were able to run these using the SDK.

> **Note**
> [ClusterTasks are being deprecated.](https://cloud.redhat.com/blog/migration-from-clustertasks-to-tekton-resolvers-in-openshift-pipelines#:~:text=First%2C%20cluster%20tasks,change%20into%20account.)

This would be useful for certain use cases, such as building containers via pipelines e.g. using [buildah](https://hub.tekton.dev/tekton/task/buildah).

### Describe alternatives you've considered

Maybe you could rewrite the existing available tasks using custom [pipeline components](https://www.kubeflow.org/docs/components/pipelines/v1/sdk/component-development/), however having to rewrite existing code is a tedious task.

As of writing, the only way I could think of to achieve the requested feature is to modify yaml generated by the SDK e.g. using sed and inserting a [taskRef like this](https://github.com/piotrpdev/azureml-model-to-edge/blob/480ba41f349a0d05366a5d47e3266f44e6185f3a/tekton/azureml-container-pipeline/azureml-container-pipeline.yaml#L60-L89)

**Comment by HumairAK** [comment]
Hey @piotrpdev, 

I believe this question was posed in an internal RH chat, I'll echo @strangiato and @mamurak 's statements here: 

> Max: 
>
> I believe DSP is not a good fit for your use case. DSP / the Kubeflow Pipelines engine uses Tekton as a backend, but it's not based on Tekton concepts. KFP comes with its own domain specific language that does not cover Tekton.
Data Science Pipelines is more centered around custom ML tasks defined either through the KFP SDK or Elyra.
If you already have Tekton pipelines and want to reuse existing Tekton tasks, I would recommend sticking with Tekton/OpenShift Pipelines.
>
> My 2 cents.

and:

>Trevor:
> I will second the recommendation to just use Tekton natively.  I have done some stuff with a Tekton pipeline that builds an image and triggers a Data Science Pipeline and that is fairly easy to do if you need to hand something off using the kfp_tekton library in python.
>
> I think that that, along with triggering a tekton pipeline from DSP (on my bucket list to figure out) should be something the DSP team should keep in mind as they build out the use cases/features.
>
> Alex Corvin Just a heads up I do have an end to end demo for promoting a model through a multi-tiered environment that we use to demo the MLOps Foundation service engagement.  It was build using Seldon since I created it before ModelMesh was available, but the same principles would apply for model mesh.  I would be happy to share it/demo it to you or @cchase if you guys are interested.

In general I agree with their statements that this seems like your usecase is better fit for ocp pipelines/tekton.

I think in DSP/KFP land the question ought to be phrased from DSP/KFP perspective (agnostic of the backend), e.g: "How can I launch k8s resources (e.g. tekton clustertasks) via dsp pipeline using the kfp sdk, so that I may xyz?" 

The fact the user sees a pipelinerun at all (when creating their pipelines via sdk) is mostly a technicality, in V2 for example, the user is never exposed to any tekton artifacts, there is a backend engine agnostic "Pipeline" resource the user will see with no mention of argo/tekton etc.
