### ISSUE TITLE
[Feature request] Continuous streaming of logs emitted from KFP component pod

### ISSUE THREAD

**Issue by yuanchi2807** [opendatahub-io/data-science-pipelines-tekton#71]
**Description:**
When a KFP component launches a scale out cluster such as codeflare/ray or spark, the application logs need to continue flowing back to the data science pipeline UI. In many large scale processing use cases, the said runs could take hours and days to complete. Pipeline launcher needs to the ability to monitor processing errors so a failed execution could be terminated early if needed. 

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by HumairAK** [comment]
@yuanchi2807 this sounds like a UI feature request, with now odh-dashboard having dsp support in it's upstream, maybe you can create this issue here on how you envision this could like like there: 

https://github.com/opendatahub-io/odh-dashboard/issues/1247 

and maybe the UI team can formulate a user story around this.  

There is currently work underway on [adding logging ](https://github.com/opendatahub-io/odh-dashboard/issues/1247), which might be related to this.

Going to close this as this is (at least for now until we have a concrete UI feature request) unrelated to backend.

**Comment by yuanchi2807** [comment]
Agree to close. Thank you.
